---
name: Build & Push

on:
  release:
    types: [published]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # check-out repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.RELEASE_TOKEN }}
          fetch-depth: 0
      # login to container registry
      - name: Login to GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.RELEASE_TOKEN }}
      # build & push
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}, ghcr.io/${{ github.repository }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.title=PYTHON_PROJECT
            org.opencontainers.image.version=${{ github.ref_name }}
          target: production
          github-token: ${{ secrets.RELEASE_TOKEN }}
